services:
  server:
    build:
      context: .
      dockerfile: docker/app_base
      target: appserver_dev
    ports:
      - 8675:8675
    volumes:
      - ./:/app
      - ./log:/log
    environment:
      - AGENT_JUMBO_LOG_LEVEL=DEBUG
      - AGENT_JUMBO_DEBUG=True
    depends_on:
      db:
        condition: service_healthy

  db:
    image: postgres
    restart: always
    user: postgres
    volumes:
      - ./db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=example
      - POSTGRES_PASSWORD=8675309jenny
      - PGDATA=/var/lib/postgresql/data/pgdata
    expose:
      - 5432
    healthcheck:
      test: [ "CMD", "pg_isready" ]
      interval: 10s
      timeout: 5s
      retries: 5
