"""add ingested_at datestamp

Revision ID: 6c5b9a0941c8
Revises: 01285cd83570
Create Date: 2024-03-24 03:45:03.633504

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6c5b9a0941c8'
down_revision = '01285cd83570'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('statuses', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ingested_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('statuses', schema=None) as batch_op:
        batch_op.drop_column('ingested_at')

    # ### end Alembic commands ###
